--[[
    init.lua
    Created: 03/30/2025 16:03:16
    Description: Autogenerated script file for the map 1_mellow_town.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local 1_mellow_town = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---1_mellow_town.Init(zone)
--Engine callback function
function 1_mellow_town.Init(zone)


end

---1_mellow_town.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function 1_mellow_town.EnterSegment(zone, rescuing, segmentID, mapID)


end

---1_mellow_town.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function 1_mellow_town.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---1_mellow_town.Rescued(zone, name, mail)
--Engine callback function
function 1_mellow_town.Rescued(zone, name, mail)


end

return 1_mellow_town

