--[[
    init.lua
    Created: 04/02/2025 20:44:04
    Description: Autogenerated script file for the map minior_wishing_woods.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local minior_wishing_woods = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---minior_wishing_woods.Init(zone)
--Engine callback function
function minior_wishing_woods.Init(zone)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> wishing_woods")
end

---minior_wishing_woods.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function minior_wishing_woods.EnterSegment(zone, rescuing, segmentID, mapID)


end

---minior_wishing_woods.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function minior_wishing_woods.ExitSegment(zone, result, rescue, segmentID, mapID)
  if segmentID == 0 then
    COMMON.EndDungeonDay(result, '1_mellow_town', -1, 0, 0)
  else
    PrintInfo("No exit procedure found!")
  COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
  end
end

---minior_wishing_woods.Rescued(zone, name, mail)
--Engine callback function
function minior_wishing_woods.Rescued(zone, name, mail)


end

return minior_wishing_woods
