--[[
    init.lua
    Created: 04/07/2025 20:04:13
    Description: Autogenerated script file for the map frigid_lake.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local frigid_lake = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---frigid_lake.Init(zone)
--Engine callback function
function frigid_lake.Init(zone)


end

---frigid_lake.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function frigid_lake.EnterSegment(zone, rescuing, segmentID, mapID)


end

---frigid_lake.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function frigid_lake.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---frigid_lake.Rescued(zone, name, mail)
--Engine callback function
function frigid_lake.Rescued(zone, name, mail)


end

return frigid_lake

