--[[
    init.lua
    Created: 04/07/2025 20:04:13
    Description: Autogenerated script file for the map frigid_lake.
]]--
-- Commonly included lua functions and data
require 'minior_jam_game.common'

-- Package name
local frigid_lake = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---frigid_lake.Init(zone)
--Engine callback function
function frigid_lake.Init(zone)


end

---frigid_lake.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function frigid_lake.EnterSegment(zone, rescuing, segmentID, mapID)


end

---frigid_lake.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function frigid_lake.ExitSegment(zone, result, rescue, segmentID, mapID)
  PrintInfo("=>> ExitSegment_frigid_lake result "..tostring(result).." segment "..tostring(segmentID).."\n\n\n")

  COMMON.DungeonEndDialogue(result)
  local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)
  if exited == true then
    -- do nothing???
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)
  else
    COMMON.UnlockWithFanfare('magma_tunnel', true)
    COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)
  end
end

---frigid_lake.Rescued(zone, name, mail)
--Engine callback function
function frigid_lake.Rescued(zone, name, mail)


end

return frigid_lake
