--[[
    init.lua
    Created: 03/23/2025 16:25:49
    Description: Autogenerated script file for the map crash_site.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local crash_site = {}

-------------------------------
-- Map Callbacks
-------------------------------
---crash_site.Init(map)
--Engine callback function
function crash_site.Init(map)


end

---crash_site.Enter(map)
--Engine callback function
function crash_site.Enter(map)

  crash_site.cutscene1()
end

---crash_site.Exit(map)
--Engine callback function
function crash_site.Exit(map)


end

---crash_site.Update(map)
--Engine callback function
function crash_site.Update(map)


end

---crash_site.GameSave(map)
--Engine callback function
function crash_site.GameSave(map)


end

---crash_site.GameLoad(map)
--Engine callback function
function crash_site.GameLoad(map)


  crash_site.cutscene1()
end

-------------------------------
-- Entities Callbacks
-------------------------------

function crash_site.cutscene1()
  GAME:CutsceneMode(true)
  UI:ResetSpeaker()
  COMMON:RespawnAllies() --Setup partner to spawn
  GAME:MoveCamera(192, 430, 1, false)
  local player = CH("PLAYER")
  local partner = CH("PARTNER")
  GROUND:CharSetAnim(player, "Sleep", true)
  --** Cutscene starts here**--
  GAME:MoveCamera(0, 0, 120, true)
  GROUND:MoveToPosition(partner, 184, 275, false, 3)

  GAME:FadeIn(20)
  GAME:WaitFrames(30)
  --Start talking
  GROUND:CharSetEmote(partner, "shock", 1)
  SOUND:PlaySE("Battle/EVT_Emote_Shock")
  GAME:WaitFrames(30)
  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("surprised")
  UI:WaitShowDialogue("Hey![pause=20] Are you okay?!")
  -- Minior form change
  GROUND:CharSetAnim(player, "Charge", true)
  GAME:WaitFrames(30)
  --  Anim
  local emitter = RogueEssence.Content.SingleEmitter(RogueEssence.Content.AnimData("Rock_Smash_Front", 3))
  emitter.LocHeight = 8
  GROUND:PlayVFX(emitter, player.Bounds.Center.X, player.Bounds.Center.Y)
  SOUND:PlaySE("Battle/_UNK_DUN_Break")
  -- Actual Change
  local form = player.CurrentForm
  local newForm = RogueEssence.Dungeon.MonsterID(form.Species, form.Form+7, form.Skin, form.Gender)
  player.Data.BaseForm = newForm
  --
  GROUND:CharSetAnim(player, "Sleep", true)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("dizzy")
  UI:WaitShowDialogue("Owww....")

  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("What happened to you? Did you...[pause=20] fall out of the sky?")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("There was a fight...[pause=30] My friends and I got hit...[pause=30]")
  GROUND:CharSetAnim(player, "Idle", false)
  GROUND:CharSetEmote(player, "shock", 1)
  SOUND:PlaySE("Battle/EVT_Emote_Shock")
  GAME:WaitFrames(30)
  UI:SetSpeakerEmotion("crying")
  UI:WaitShowDialogue("My friends! Where are they?")
  UI:WaitShowDialogue("They all fell with me, but I lost them on the way down!")

  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Shouting")
  UI:WaitShowDialogue("Hey![pause=30] Just calm down, you're not making any sense!")
  UI:SetSpeakerEmotion("Normal")
  --** Cutscene ends here**--
  GAME:CutsceneMode(false)
end

return crash_site
