--[[
    init.lua
    Created: 03/22/2025 14:25:06
    Description: Autogenerated script file for the map 1_jam_intro.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local 1_jam_intro = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---1_jam_intro.Init(zone)
--Engine callback function
function 1_jam_intro.Init(zone)


end

---1_jam_intro.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function 1_jam_intro.EnterSegment(zone, rescuing, segmentID, mapID)


end

---1_jam_intro.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function 1_jam_intro.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---1_jam_intro.Rescued(zone, name, mail)
--Engine callback function
function 1_jam_intro.Rescued(zone, name, mail)


end

return 1_jam_intro

