--[[
    init.lua
    Created: 04/24/2025 21:36:29
    Description: Autogenerated script file for the map dreamscape_cavern_pit.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local dreamscape_cavern_pit = {}

-------------------------------
-- Map Callbacks
-------------------------------
---dreamscape_cavern_pit.Init(map)
--Engine callback function
function dreamscape_cavern_pit.Init(map)
  COMMON:RespawnAllies()
  for i = 0, GAME:GetPlayerPartyCount() - 1, 1 do
		chara = GAME:GetPlayerPartyMember(i)
		chara:FullRestore()
	end
  if SV.mindscape_cavern.BossDefeated ~= true then
    dreamscape_cavern_pit.CutscenePreBoss()
  else
    dreamscape_cavern_pit.CutscenePostBoss()
  end

end

---dreamscape_cavern_pit.Enter(map)
--Engine callback function
function dreamscape_cavern_pit.Enter(map)

  GAME:FadeIn(20)

end

---dreamscape_cavern_pit.Exit(map)
--Engine callback function
function dreamscape_cavern_pit.Exit(map)


end

---dreamscape_cavern_pit.Update(map)
--Engine callback function
function dreamscape_cavern_pit.Update(map)


end

---dreamscape_cavern_pit.GameSave(map)
--Engine callback function
function dreamscape_cavern_pit.GameSave(map)


end

---dreamscape_cavern_pit.GameLoad(map)
--Engine callback function
function dreamscape_cavern_pit.GameLoad(map)

  GAME:FadeIn(20)

end

function dreamscape_cavern_pit.CutscenePreBoss()
  GAME:CutsceneMode(true)
  --Get characters
  local player = CH("PLAYER")
  local partner = CH("TEAMMATE1")
  local jirachi = CH("BOSS_Jirachi")

  if SV.mindscape_cavern.BossAttempted ~= true then --First time
    GROUND:CharSetAnim(jirachi, "sleep", true)
    --Start
    GAME:FadeIn(20)
    local coro1 = TASK:BranchCoroutine(function() GROUND:MoveToPosition(player, 144, 216, false, 2) end)
    local coro2 = TASK:BranchCoroutine(function() GROUND:MoveToPosition(partner, 168, 216, false, 2) end)
    TASK:JoinCoroutines({coro1, coro2})

    GROUND:CharSetEmote(partner, "shock", 1)
    GAME:WaitFrames(30)
    UI:SetSpeaker(partner)
    UI:SetSpeakerEmotion("surprised")
    UI:WaitShowDialogue("Look, up there![pause=0] That must be " ..jirachi:GetDisplayName()..".")

    GAME:MoveCamera(0, -72, 24, true)

    UI:SetSpeakerEmotion("shouting")
    UI:WaitShowDialogue("Hey![pause=20] Wake up!")

    UI:SetSpeaker(jirachi)
    UI:SetSpeakerEmotion("special1")
    UI:WaitShowDialogue("[speed=0.5]Hmmm?[pause=30] I am " ..jirachi:GetDisplayName()..", yes.")
    UI:WaitShowDialogue("[speed=0.5]What is it you seek?")

    GROUND:CharSetEmote(partner, "angry", 1)
    SOUND:PlaySE("Battle/EVT_Emote_Complain_2")
    GAME:WaitFrames(30)
    UI:SetSpeaker(partner)
    UI:SetSpeakerEmotion("angry")
    UI:WaitShowDialogue("We're here for answers![pause=0] We want to know what you did to [color=#00F8F8]Rayquaza[color]!")

    UI:SetSpeaker(jirachi)
    UI:SetSpeakerEmotion("special1")
    UI:WaitShowDialogue("[speed=0.5]Oh?[pause=30] I think I know who you are,[pause=10] now.")
    UI:WaitShowDialogue("[speed=0.5]I granted your wish.[pause=30] You're " ..partner:GetDisplayName()..".")

    GROUND:CharSetEmote(partner, "shock", 1)
    GAME:WaitFrames(30)
    UI:SetSpeaker(partner)
    UI:SetSpeakerEmotion("surprised")
    UI:WaitShowDialogue("So it's true![pause=20] You really did grant my wish!")

    UI:SetSpeaker(jirachi)
    UI:SetSpeakerEmotion("special1")
    UI:WaitShowDialogue("[speed=0.5]Yes...[pause=30] A selfish, selfish, selfish little wish.")
    UI:WaitShowDialogue("[speed=0.5]Little " ..partner:GetDisplayName().. " wanted a friend, so made a wish.")
    UI:WaitShowDialogue("[speed=0.5]Then down from the sky fell a little [color=#009800]Minior[color].[pause=0] The bestest friend you could ever wish for.")


    UI:SetSpeaker(partner)
    UI:SetSpeakerEmotion("determined")
    UI:WaitShowDialogue("I need to know...[pause=30] My wish,[pause=20] why did my wish make [color=#00F8F8]Rayquaza[color] go crazy!?")

    UI:SetSpeaker(jirachi)
    UI:SetSpeakerEmotion("special1")
    UI:WaitShowDialogue("[speed=0.5]Because I was bored.[pause=0] I wanted to see what would happen.")

    GROUND:CharSetEmote(partner, "angry", 1)
    SOUND:PlaySE("Battle/EVT_Emote_Complain_2")
    GAME:WaitFrames(30)
    UI:SetSpeaker(partner)
    UI:SetSpeakerEmotion("angry")
    UI:WaitShowDialogue("Then... then it's all your fault!")

    UI:SetSpeaker(jirachi)
    UI:SetSpeakerEmotion("special1")
    UI:WaitShowDialogue("[speed=0.5]Nope...[pause=30] Wrong again.[pause=0] You made the wish. You live with the consequences.")
    UI:WaitShowDialogue("[speed=0.5]Eeeeeeverything that's happened since...[pause=30] It's all your fault!")

    GROUND:CharSetEmote(partner, "sweating", 1)
    SOUND:PlaySE("Battle/EVT_Emote_Sweating")
    GAME:WaitFrames(30)
    UI:SetSpeaker(partner)
    UI:SetSpeakerEmotion("sad")
    UI:WaitShowDialogue("Then undo it.")

    GROUND:CharSetEmote(player, "shock", 1)
    GROUND:CharSetEmote(jirachi, "shock", 1)
    SOUND:PlaySE("Battle/EVT_Emote_Startled_2")
    GAME:WaitFrames(30)
    UI:WaitShowDialogue("If my wish was the cause of all of this...[pause=30] You can undo it, and make it so nobody got hurt.\nRight?")

    GROUND:CharTurnToChar(player, partner)
    UI:SetSpeaker(player)
    UI:WaitShowDialogue(partner:GetDisplayName()..", you can't mean that?")

    UI:SetSpeaker(jirachi)
    UI:SetSpeakerEmotion("special1")
    UI:WaitShowDialogue("Oh...[pause=30] But they do.")
    UI:WaitShowDialogue("What an interesting proposition.")
    local center = GAME:GetCameraCenter()
    local emitter = RogueEssence.Content.FlashEmitter()
    emitter.FadeInTime = 2
    emitter.HoldTime = 2
    emitter.FadeOutTime = 2
    emitter.StartColor = Color(0, 0, 0, 0)
    emitter.Layer = DrawLayer.Top
    emitter.Anim = RogueEssence.Content.BGAnimData("White", 0)
    GROUND:PlayVFX(emitter, center.X, center.Y)
    SOUND:PlayBattleSE("EVT_Battle_Flash")
    GAME:WaitFrames(16)
    GROUND:CharEndAnim(jirachi)
    UI:SetSpeakerEmotion("normal")
    UI:WaitShowDialogue("Okay then.[pause=30] If you can defeat me, I'll undo your wish.")

    GROUND:CharTurnToChar(player, jirachi)

    UI:SetSpeaker(partner)
    UI:SetSpeakerEmotion("determined")
    UI:WaitShowDialogue("Fine then! If that's what it takes!")
    UI:WaitShowDialogue("But we won't lose to the likes of you!")

    GROUND:MoveInDirection(jirachi, Direction.Down, 12, false, 2)
    GAME:MoveCamera(0, 0, 24, true)

    UI:SetSpeaker(jirachi)
    UI:SetSpeakerEmotion("determined")
    UI:WaitShowDialogue("Prove to me you have the right to change fate!")

    SV.mindscape_cavern.BossAttempted = true
  else --Repeat attempts
    GROUND:CharSetAnim(jirachi, "sleep", true)
    --Start
    GAME:FadeIn(20)
    local coro1 = TASK:BranchCoroutine(function() GROUND:MoveToPosition(player, 144, 216, false, 2) end)
    local coro2 = TASK:BranchCoroutine(function() GROUND:MoveToPosition(partner, 168, 216, false, 2) end)
    TASK:JoinCoroutines({coro1, coro2})

    GAME:MoveCamera(0, -72, 24, true)

    UI:SetSpeaker(jirachi)
    UI:SetSpeakerEmotion("special1")
    UI:WaitShowDialogue("[speed=0.5]Hmmm?[pause=30] Back again so soon?[pause=0] You're very determined.")

    UI:SetSpeaker(partner)
    UI:SetSpeakerEmotion("determined")
    UI:WaitShowDialogue("We're not going down again so easily!")

    local center = GAME:GetCameraCenter()
    local emitter = RogueEssence.Content.FlashEmitter()
    emitter.FadeInTime = 2
    emitter.HoldTime = 2
    emitter.FadeOutTime = 2
    emitter.StartColor = Color(0, 0, 0, 0)
    emitter.Layer = DrawLayer.Top
    emitter.Anim = RogueEssence.Content.BGAnimData("White", 0)
    GROUND:PlayVFX(emitter, center.X, center.Y)
    SOUND:PlayBattleSE("EVT_Battle_Flash")
    GAME:WaitFrames(16)
    GROUND:CharEndAnim(jirachi)
    UI:SetSpeakerEmotion("normal")

    UI:SetSpeaker(jirachi)
    UI:WaitShowDialogue("How glad I am to hear that.")

    GROUND:MoveInDirection(jirachi, Direction.Down, 12, false, 2)
    GAME:MoveCamera(0, 0, 24, true)

    UI:SetSpeaker(jirachi)
    UI:SetSpeakerEmotion("determined")
    UI:WaitShowDialogue("Prove to me you have the right to change fate!")

  end
  GAME:CutsceneMode(false)

  COMMON:BossTransition()

  GAME:ContinueDungeon('mindscape_cavern', 2, 0, 0)
  --End
  GAME:CutsceneMode(false)
end

function dreamscape_cavern_pit.CutscenePostBoss()
  --Get characters
  GAME:CutsceneMode(true)
  --Get characters
  local player = CH("PLAYER")
  local partner = CH("TEAMMATE1")
  local jirachi = CH("BOSS_Jirachi")
  -- Set locations
  GROUND:CharSetAnim(jirachi, "charge", true)
  GROUND:TeleportTo(player, 144, 168, Direction.Up)
  GROUND:TeleportTo(partner, 168, 168, Direction.Up)

  --Start
  GAME:FadeIn(20)
  UI:SetSpeaker(jirachi)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Ha...[pause=30][emote=joyous]hahahahahahaha!")
  GROUND:CharEndAnim(jirachi) --stops a looping animation
  UI:WaitShowDialogue("What fun that was![pause=0] You are stronger than you look.")

  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Alright, we beat you![pause=30] Now undo the wish!")

  UI:SetSpeaker(jirachi)
  UI:WaitShowDialogue("No.")

  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("What?![emote=angry] But you said you would! We had a deal!")

  UI:SetSpeaker(jirachi)
  UI:WaitShowDialogue("A wish cannot be undone.[pause=0][emote=happy] Besides, it all worked out in the end, right?")
  UI:WaitShowDialogue("You got what you wanted:[pause=30] A friend,[pause=10] an awesome adventure?")

  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Angry")
  UI:WaitShowDialogue("No! I didn't want this![pause=0] People got hurt because you used my wish for your own selfish gain!")
  UI:SetSpeakerEmotion("Sad")
  UI:WaitShowDialogue("[color=#F8A0F8]Team Glamour[color]...[pause=20] And [color=#F8A0F8]Team Vanguard[color] too!")
  UI:WaitShowDialogue("[color=#00F8F8]Granbull[color] is still missing...")
  UI:SetSpeakerEmotion("Angry")
  UI:WaitShowDialogue("You abused your power, and now innocent people are suffering![pause=0] You have a duty to make it right!")

  GROUND:CharSetEmote(jirachi, "sweatdrop", 1)
  SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
  GAME:WaitFrames(30)
  UI:SetSpeaker(jirachi)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("[speed=0.9]Maybe I do...[pause=30] Maybe I don't.[pause=0] It doesn't matter now,[pause=10] anyway.")
  UI:SetSpeakerEmotion("Special0")
  UI:WaitShowDialogue("[speed=0.8]It's time for me to sleep for a long time.[pause=0] When I wake, you won't be here to annoy me.")
  UI:WaitShowDialogue("[speed=0.7]Thanks for the battle...[pause=30] It was the most fun I've had...[pause=35] In a long time...")

  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("Wait![pause=30] You can't just go to sleep!")

  UI:SetSpeaker(jirachi)
  UI:SetSpeakerEmotion("Special0")
  UI:WaitShowDialogue("[speed=0.7]Sorry...[pause=30] I don't make the rules...[pause=30] One wish per person, once every thousand years...")
  GROUND:CharSetAnim(jirachi, "sleep", true)
  UI:WaitShowDialogue("[speed=0.6]Then it's back to sleep...")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("[sound=](One wish per person...)")

  GAME:WaitFrames(30)

  GROUND:CharSetEmote(player, "shock", 1)
  SOUND:PlaySE("Battle/EVT_Emote_Exclaim_Realized")
  GAME:WaitFrames(30)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("[sound=](I've got it!)")
  UI:WaitShowDialogue(jirachi:GetDisplayName()..", before you sleep![pause=30] Can you grant me a wish?")

  UI:SetSpeaker(jirachi)
  UI:SetSpeakerEmotion("Special0")
  UI:WaitShowDialogue("[speed=0.6]I suppose...[pause=30] But make it quick...")
  UI:WaitShowDialogue("[speed=0.6]Then it's back to sleep...")

  GROUND:CharTurnToChar(player, partner)
  GROUND:CharTurnToChar(partner, player)

  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("Good thinking, " ..player:GetDisplayName().."![pause=0] You can wish for something that will set everything right!")

  GROUND:CharTurnToChar(player, jirachi)
  GROUND:CharTurnToChar(partner, jirachi)

  UI:SetSpeaker(jirachi)
  UI:SetSpeakerEmotion("Special1")
  local choices = {"Unlimited Power!", "All the money in the world!", "I wish everyone would get home safely."}
  local wrongChoice = true
  while( wrongChoice == true) do
    UI:SetSpeaker(jirachi)
    UI:SetSpeakerEmotion("Special1")
    UI:BeginChoiceMenu("[speed=0.5]What will you wish for?", choices, 1, 3)
    UI:WaitForChoice()
    result = UI:ChoiceResult()
    if result == 3 then
      wrongChoice = false
    else
      UI:SetSpeaker(partner)
      UI:WaitShowDialogue(player:GetDisplayName().. "...[pause=30] You need to wish for something that will set everything right!")
    end
  end
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("I wish...[pause=30] For everyone to get home safely!")

  UI:SetSpeaker(jirachi)
  UI:SetSpeakerEmotion("Special1")
  UI:WaitShowDialogue("[speed=0.4]Your wish...")
  local center = GAME:GetCameraCenter()
  local emitter = RogueEssence.Content.FlashEmitter()
  emitter.FadeInTime = 2
  emitter.HoldTime = 2
  emitter.FadeOutTime = 2
  emitter.StartColor = Color(0, 0, 0, 0)
  emitter.Layer = DrawLayer.Top
  emitter.Anim = RogueEssence.Content.BGAnimData("White", 0)
  GROUND:PlayVFX(emitter, center.X, center.Y)
  SOUND:PlayBattleSE("EVT_Battle_Flash")
  GAME:WaitFrames(16)
  UI:WaitShowDialogue("[speed=0.3]Is...[pause=30][speed=0.2] Granted.....")

  GAME:WaitFrames(120)
  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("What...[pause=30] What do we do now?")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Sad")
  UI:WaitShowDialogue("We go home.[pause=0] Which means...")

  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Sad")
  UI:WaitShowDialogue("Back to [color=#F8C060]Stardust Peak[color]...")

  --End
  SV.stardust_peak.CanDoEndingTrue = true
  GAME:CutsceneMode(false)
  COMMON.EndDungeonDay(RogueEssence.Data.GameProgress.ResultType.Cleared, 'stardust_peak', -1, 1, 0)
end

-------------------------------
-- Entities Callbacks
-------------------------------


return dreamscape_cavern_pit
