--[[
    init.lua
    Created: 04/03/2025 19:42:39
    Description: Autogenerated script file for the map windswept_trail.
]]--
-- Commonly included lua functions and data
require 'minior_jam_game.common'

-- Package name
local windswept_trail = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---windswept_trail.Init(zone)
--Engine callback function
function windswept_trail.Init(zone)


end

---windswept_trail.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function windswept_trail.EnterSegment(zone, rescuing, segmentID, mapID)


end

---windswept_trail.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function windswept_trail.ExitSegment(zone, result, rescue, segmentID, mapID)
  PrintInfo("=>> ExitSegment_windswept_trail result "..tostring(result).." segment "..tostring(segmentID).."\n\n\n")

  COMMON.DungeonEndDialogue(result)
  local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)
  if exited == true then
    -- do nothing???
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)
  else
    if segmentID == 0 then
      COMMON.UnlockWithFanfare('verdant_meadow', true)
      SV.mellow_town.CanDoCutsceneGlamour1 = true
      COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)
    elseif segmentID == 1 then
      COMMON.UnlockWithFanfare('frigid_lake', true)
      SV.mellow_town.CanDoCutsceneGlamour1 = true
      COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)
    else
      PrintInfo("No exit procedure found!")
	    COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
    end
  end
end
  -- print(tostring(result))
  -- if result == 0 then --Actually won
  --   if segmentID == 0 then
  --     COMMON.UnlockWithFanfare('verdant_meadow', true)
  --   elseif segmentID == 1 then
  --     COMMON.UnlockWithFanfare('frigid_lake', true)
  --   end
  -- elseif result == 1 then
  --   UI:SetSpeaker(GAME:GetPlayerPartyMember(1))
  --   UI:SetSpeakerEmotion("Pain")
  --   UI:WaitShowDialogue("Urk...[pause=20] This is harder than I thought...[pause=20] Let's head home for now...")
  -- end
  -- COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)

---windswept_trail.Rescued(zone, name, mail)
--Engine callback function
function windswept_trail.Rescued(zone, name, mail)


end

return windswept_trail
