--[[
    init.lua
    Created: 04/03/2025 19:42:39
    Description: Autogenerated script file for the map windswept_trail.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local windswept_trail = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---windswept_trail.Init(zone)
--Engine callback function
function windswept_trail.Init(zone)


end

---windswept_trail.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function windswept_trail.EnterSegment(zone, rescuing, segmentID, mapID)


end

---windswept_trail.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function windswept_trail.ExitSegment(zone, result, rescue, segmentID, mapID)
  PrintInfo("=>> ExitSegment_windswept_trail result "..tostring(result).." segment "..tostring(segmentID))
  if segmentID == 0 then
    COMMON.UnlockWithFanfare('verdant_meadow', true)
  elseif segmentID == 1 then
    COMMON.UnlockWithFanfare('frigid_lake', true)
  end
  COMMON.EndDungeonDay(result, 'mellow_town', -1, 0,0)
end

---windswept_trail.Rescued(zone, name, mail)
--Engine callback function
function windswept_trail.Rescued(zone, name, mail)


end

return windswept_trail
