--[[
    init.lua
    Created: 04/08/2025 18:57:17
    Description: Autogenerated script file for the map magma_tunnel.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local magma_tunnel = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---magma_tunnel.Init(zone)
--Engine callback function
function magma_tunnel.Init(zone)


end

---magma_tunnel.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function magma_tunnel.EnterSegment(zone, rescuing, segmentID, mapID)


end

---magma_tunnel.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function magma_tunnel.ExitSegment(zone, result, rescue, segmentID, mapID)
  PrintInfo("=>> ExitSegment_magma_tunnel result "..tostring(result).." segment "..tostring(segmentID).."\n\n\n")

  local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)
  if exited == true then
    -- do nothing???
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    UI:SetSpeaker(GAME:GetPlayerPartyMember(1))
    UI:SetSpeakerEmotion("Pain")
    UI:WaitShowDialogue("Urk...[pause=20] This is harder than I thought...[pause=20] Let's head home for now...")
    COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
  else
    -- OMMON.UnlockWithFanfare('lunar_barrow', true) #Not implemented yet
    COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)
  end
  local quest = SV.missions.Missions["OrangeMiniorRescue"]
  if quest ~= nil then
    if quest.Complete == COMMON.MISSION_COMPLETE then
      UI:WaitShowDialogue("You rescued Orange Minior!") -- Test dialogue
      COMMON.CompleteMission("OrangeMiniorRescue")
    end
  end
end

---magma_tunnel.Rescued(zone, name, mail)
--Engine callback function
function magma_tunnel.Rescued(zone, name, mail)


end

return magma_tunnel
