--[[
    init.lua
    Created: 04/10/2025 21:15:36
    Description: Autogenerated script file for the map primal_canyon.
]]--
-- Commonly included lua functions and data
require 'minior_jam_game.common'

-- Package name
local primal_canyon = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---primal_canyon.Init(zone)
--Engine callback function
function primal_canyon.Init(zone)


end

---primal_canyon.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function primal_canyon.EnterSegment(zone, rescuing, segmentID, mapID)


end

---primal_canyon.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function primal_canyon.ExitSegment(zone, result, rescue, segmentID, mapID)
  PrintInfo("=>> ExitSegment_primal_canyon result "..tostring(result).." segment "..tostring(segmentID).."\n\n\n")

  COMMON.DungeonEndDialogue(result)
  local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)
  if exited == true then
    -- do nothing???
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)
  else
    COMMON.UnlockWithFanfare('stardust_peak', true)
    COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)
    SV.mellow_town.CanDoCutsceneVanguard1 = true
  end
end


---primal_canyon.Rescued(zone, name, mail)
--Engine callback function
function primal_canyon.Rescued(zone, name, mail)


end

return primal_canyon
