--[[
    init.lua
    Created: 04/24/2025 20:18:58
    Description: Autogenerated script file for the map mindscape_cavern.
]]--
-- Commonly included lua functions and data
require 'minior_jam_game.common'

-- Package name
local mindscape_cavern = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---mindscape_cavern.Init(zone)
--Engine callback function
function mindscape_cavern.Init(zone)


end

---mindscape_cavern.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function mindscape_cavern.EnterSegment(zone, rescuing, segmentID, mapID)


end

---mindscape_cavern.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function mindscape_cavern.ExitSegment(zone, result, rescue, segmentID, mapID)
  PrintInfo("=>> ExitSegment_mindscape_cavern result "..tostring(result).." segment "..tostring(segmentID).."\n\n\n")

  COMMON.DungeonEndDialogue(result)
  local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)
  if exited == true then
    -- do nothing???
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)
  else
    --COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)
    if segmentID == 0 then --exiting from first half of dungeon
      GAME:EnterZone("mindscape_cavern", -1, 0, 0)
    elseif segmentID == 1 then --Exiting from second half of dungeon
      if SV.mindscape_cavern.BossDefeated ~= true then
        GAME:EnterZone("mindscape_cavern", -1, 1, 0) -- Send to ground map for cutscene
      else
        GAME:EndDungeonDay(result, "mellow_town", -1, 0, 1)
      end
    elseif segmentID == 2 then --exiting from boss room
      SV.mindscape_cavern.BossDefeated = true
      GAME:EnterZone("mindscape_cavern", -1, 1, 0) -- Send to ground map for cutscene
    end
  end
end

---mindscape_cavern.Rescued(zone, name, mail)
--Engine callback function
function mindscape_cavern.Rescued(zone, name, mail)


end

return mindscape_cavern
