--[[
    init.lua
    Created: 04/05/2025 19:42:47
    Description: Autogenerated script file for the map verdant_meadow.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local verdant_meadow = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---verdant_meadow.Init(zone)
--Engine callback function
function verdant_meadow.Init(zone)


end

---verdant_meadow.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function verdant_meadow.EnterSegment(zone, rescuing, segmentID, mapID)


end

---verdant_meadow.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function verdant_meadow.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---verdant_meadow.Rescued(zone, name, mail)
--Engine callback function
function verdant_meadow.Rescued(zone, name, mail)


end

return verdant_meadow

