--[[
    init.lua
    Created: 04/05/2025 19:42:47
    Description: Autogenerated script file for the map verdant_meadow.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local verdant_meadow = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---verdant_meadow.Init(zone)
--Engine callback function
function verdant_meadow.Init(zone)


end

---verdant_meadow.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function verdant_meadow.EnterSegment(zone, rescuing, segmentID, mapID)
  PrintInfo("=>> ExitSegment_verdant_meadow result "..tostring(result).." segment "..tostring(segmentID).."\n\n\n")
  if result == 0 then --Actually won
      COMMON.UnlockWithFanfare('magma_tunnel', true)
  else -- Lose dialogue
    UI:SetSpeaker(GAME:GetPlayerPartyMember(1))
    UI:SetSpeakerEmotion("Pain")
    UI:WaitShowDialogue("Urk...[pause=20] This is harder than I thought...[pause=20] Let's head home for now...")
  end
  COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)

end

---verdant_meadow.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function verdant_meadow.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---verdant_meadow.Rescued(zone, name, mail)
--Engine callback function
function verdant_meadow.Rescued(zone, name, mail)


end

return verdant_meadow
