--[[
    init.lua
    Created: 04/25/2025 13:30:34
    Description: Autogenerated script file for the map stardust_peak_treasure_room.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local stardust_peak_treasure_room = {}

-------------------------------
-- Map Callbacks
-------------------------------
---stardust_peak_treasure_room.Init(map)
--Engine callback function
function stardust_peak_treasure_room.Init(map)


end

---stardust_peak_treasure_room.Enter(map)
--Engine callback function
function stardust_peak_treasure_room.Enter(map)

  GAME:FadeIn(20)

end

---stardust_peak_treasure_room.Exit(map)
--Engine callback function
function stardust_peak_treasure_room.Exit(map)


end

---stardust_peak_treasure_room.Update(map)
--Engine callback function
function stardust_peak_treasure_room.Update(map)


end

---stardust_peak_treasure_room.GameSave(map)
--Engine callback function
function stardust_peak_treasure_room.GameSave(map)


end

---stardust_peak_treasure_room.GameLoad(map)
--Engine callback function
function stardust_peak_treasure_room.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return stardust_peak_treasure_room

