--[[
    init.lua
    Created: 03/22/2025 14:26:41
    Description: Autogenerated script file for the map character_select.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local character_select = {}

-------------------------------
-- Map Callbacks
-------------------------------
---character_select.Init(map)
--Engine callback function
function character_select.Init(map)


end

---character_select.Enter(map)
--Engine callback function
function character_select.Enter(map)

  character_select.StartGame()

end

---character_select.Exit(map)
--Engine callback function
function character_select.Exit(map)


end

---character_select.Update(map)
--Engine callback function
function character_select.Update(map)


end

---character_select.GameSave(map)
--Engine callback function
function character_select.GameSave(map)


end

---character_select.GameLoad(map)
--Engine callback function
function character_select.GameLoad(map)

  character_select.StartGame()

end

-------------------------------
-- Entities Callbacks
-------------------------------
-- Function for starting the GAME
function character_select.StartGame()
  --remove any team members that may exist by default for some reason
	local party_count = _DATA.Save.ActiveTeam.Players.Count
	for ii = 1, party_count, 1 do
		_DATA.Save.ActiveTeam.Players:RemoveAt(0)
	end

	local assembly_count = GAME:GetPlayerAssemblyCount()
	for i = 1, assembly_count, 1 do
	   _DATA.Save.ActiveTeam.Assembly.RemoveAt(i-1)--not sure if this permanently deletes or not...
	end


  UI:WaitShowVoiceOver("Test", -1)
  character_select.MiniorSelect()
  character_select.PartnerSelect()
end
-- Function for choosing partner
function character_select.PartnerSelect()
  local msg = "Choose a Pokémon."
  local choices = {RogueEssence.Dungeon.MonsterID("eevee", 0, "normal", Gender.Female),
                  RogueEssence.Dungeon.MonsterID("treecko", 0, "normal", Gender.Male),
                  RogueEssence.Dungeon.MonsterID("litten", 0, "normal", Gender.Male),
                  RogueEssence.Dungeon.MonsterID("totodile", 0, "normal", Gender.Male),
                  RogueEssence.Dungeon.MonsterID("zorua", 0, "normal", Gender.Female),
                  RogueEssence.Dungeon.MonsterID("rockruff", 0, "normal", Gender.Male)}

  local continue = false
	local partner_choice = -1

	while not continue do
		UI:ChooseMonsterMenu(msg, choices)
		UI:WaitForChoice()
		local result = UI:ChoiceResult()
		partner_choice = result
		UI:ChoiceMenuYesNo("Is " .. _DATA:GetMonster(partner_choice.Species):GetColoredName() .. " correct?")
		UI:WaitForChoice()
		continue = UI:ChoiceResult()
	end

  -- Get partner nickname
  local yesnoResult = false
	while not yesnoResult do
		UI:NameMenu("What is your partner's name?", "", 60)
		UI:WaitForChoice()
		result = UI:ChoiceResult()
		--if no name given, set name to species name
		if result == "" then result = _DATA:GetMonster(partner_choice.Species).Name:ToLocal() end
		UI:ChoiceMenuYesNo("Is [color=#FFFF00]" .. result .. "[color] correct?")
		UI:WaitForChoice()
		yesnoResult = UI:ChoiceResult()
	end

  partner = _DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, partner_choice, 15, "", 0)
  tbl = LTBL(partner)
  tbl.Importance = "Partner"
  partner.IsFounder = true
  partner.IsPartner = true
  partner.Nickname = result
  _DATA.Save.ActiveTeam.Players:Add(partner)
end

-- Function for getting random playable Minior - it's a surprise!
function character_select.MiniorSelect()
  local form_rando = math.random(0,6)

  player_minior = RogueEssence.Dungeon.MonsterID("minior", form_rando, "normal", Gender.Genderless)

  -- Get player nickname
  local yesnoResult = false
	while not yesnoResult do
		UI:NameMenu("What is your name?", "", 60)
		UI:WaitForChoice()
		result = UI:ChoiceResult()
		--if no name given, set name to species name
		if result == "" then result = _DATA:GetMonster(player_minior.Species).Name:ToLocal() end
		UI:ChoiceMenuYesNo("Is [color=#FFFF00]" .. result .. "[color] correct?")
		UI:WaitForChoice()
		yesnoResult = UI:ChoiceResult()
	end

  -- Create partner, make founder, set nickname, add to (empty) party
  player = _DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, player_minior, 15, "", form_rando)
  tbl = LTBL(player)
  tbl.IsFounder = true
  player.Nickname = result
  _DATA.Save.ActiveTeam.Players:Add(player)
end


return character_select
