--[[
    init.lua
    Created: 04/20/2025 11:09:43
    Description: Autogenerated script file for the map stardust_peak_rest_stop.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local stardust_peak_rest_stop = {}

-------------------------------
-- Map Callbacks
-------------------------------
---stardust_peak_rest_stop.Init(map)
--Engine callback function
function stardust_peak_rest_stop.Init(map)
  local chara
	for i = 0, GAME:GetPlayerPartyCount() - 1, 1 do
		chara = GAME:GetPlayerPartyMember(i)
		chara:FullRestore()
	end
  COMMON.RespawnAllies()
  local partner = CH('TEAMMATE1')
  local player = CH("PLAYER")
  partner.CollisionDisabled = true
  GROUND:TeleportTo(CH("TEAMMATE1"), player.Bounds.Center.X, player.Bounds.Center.Y, Direction.Up)
  AI:SetCharacterAI(partner, "origin.ai.ground_partner", CH('PLAYER'), partner.Position)
end

---stardust_peak_rest_stop.Enter(map)
--Engine callback function
function stardust_peak_rest_stop.Enter(map)

  GAME:FadeIn(20)

end

---stardust_peak_rest_stop.Exit(map)
--Engine callback function
function stardust_peak_rest_stop.Exit(map)


end

---stardust_peak_rest_stop.Update(map)
--Engine callback function
function stardust_peak_rest_stop.Update(map)


end

---stardust_peak_rest_stop.GameSave(map)
--Engine callback function
function stardust_peak_rest_stop.GameSave(map)


end

---stardust_peak_rest_stop.GameLoad(map)
--Engine callback function
function stardust_peak_rest_stop.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function stardust_peak_rest_stop.EntranceSouth_Touch(obj, activator)
  local partner = CH("TEAMMATE1")
  local player = CH("PLAYER")
  GROUND:CharTurnToChar(player, partner)
  GROUND:CharTurnToChar(partner, player)
  UI:SetSpeaker(partner)
  UI:ChoiceMenuYesNo(STRINGS:Format("If you're not ready, we can go back to town."), false)
  UI:WaitForChoice()
  ch = UI:ChoiceResult()
  if ch then
    local result = RogueEssence.Data.GameProgress.ResultType.Escaped
    COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)
  else
    UI:WaitShowDialogue(STRINGS:Format("Okay, let's do this then!"))
  end
end

function stardust_peak_rest_stop.EntranceNorth_Touch(obj, activator)
  local partner = CH("TEAMMATE1")
  local player = CH("PLAYER")
  GROUND:CharTurnToChar(player, partner)
  GROUND:CharTurnToChar(partner, player)
  UI:SetSpeaker(partner)
  UI:ChoiceMenuYesNo(STRINGS:Format("Ready to continue, " ..player:GetDisplayName().. "?"), false)
  UI:WaitForChoice()
  ch = UI:ChoiceResult()
  if ch then
    GAME:ContinueDungeon("stardust_peak", 0, 1, 0)
  else
    UI:WaitShowDialogue(STRINGS:Format("Take your time. We can continue when you're ready."))
  end
end

function stardust_peak_rest_stop.Storage_Action(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON:ShowTeamStorageMenu()
end

return stardust_peak_rest_stop
