--[[
    init.lua
    Created: 04/21/2025 21:16:14
    Description: Autogenerated script file for the map stardust_pinnacle.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local stardust_pinnacle = {}

-------------------------------
-- Map Callbacks
-------------------------------
---stardust_pinnacle.Init(map)
--Engine callback function
function stardust_pinnacle.Init(map)
  COMMON.RespawnAllies()
  local silvally = CH("NPC_Silvally")
  local ceruledge = CH("NPC_Ceruledge")
  local noivern = CH("NPC_Noivern")
  GROUND:CharSetAction(silvally, RogueEssence.Ground.PoseGroundAction(silvally.Position, silvally.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Pain")))
  GROUND:CharSetAction(ceruledge, RogueEssence.Ground.PoseGroundAction(ceruledge.Position, ceruledge.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Sleep")))
  GROUND:CharSetAction(noivern, RogueEssence.Ground.PoseGroundAction(noivern.Position, noivern.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Sleep")))
end

---stardust_pinnacle.Enter(map)
--Engine callback function
function stardust_pinnacle.Enter(map)

  GAME:FadeIn(20)

end

---stardust_pinnacle.Exit(map)
--Engine callback function
function stardust_pinnacle.Exit(map)


end

---stardust_pinnacle.Update(map)
--Engine callback function
function stardust_pinnacle.Update(map)


end

---stardust_pinnacle.GameSave(map)
--Engine callback function
function stardust_pinnacle.GameSave(map)


end

---stardust_pinnacle.GameLoad(map)
--Engine callback function
function stardust_pinnacle.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return stardust_pinnacle
