--[[
    init.lua
    Created: 04/20/2025 11:00:25
    Description: Autogenerated script file for the map stardust_peak.
]]--
-- Commonly included lua functions and data
require 'minior_jam_game.common'

-- Package name
local stardust_peak = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---stardust_peak.Init(zone)
--Engine callback function
function stardust_peak.Init(zone)


end

---stardust_peak.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function stardust_peak.EnterSegment(zone, rescuing, segmentID, mapID)


end

---stardust_peak.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function stardust_peak.ExitSegment(zone, result, rescue, segmentID, mapID)
  PrintInfo("=>> ExitSegment_stardust_peak result "..tostring(result).." segment "..tostring(segmentID).."\n\n\n")
  GAME:RemovePlayerGuest(1) --Always remove guests when leaving stardust peak, regardless of how
  GAME:RemovePlayerGuest(0)

  COMMON.DungeonEndDialogue(result)
  local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)
  if exited == true then
    -- do nothing
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    COMMON.EndDungeonDay(result, 'mellow_town', -1, 0, 1)
  else
    if segmentID == 0 then --Exiting from first half of dungeon
      GAME:EnterZone("stardust_peak", -1, 0, 0)
    elseif segmentID == 1 then --Exiting from second half of dungeon
      if SV.stardust_peak.BossDefeated == true then
        GAME:EnterZone("stardust_peak", -1, 1, 0) -- Send to ground map for cutscene
      else --Boss not defeated
        GAME:EnterZone("stardust_peak", -1, 1, 0) -- Send to ground map for cutscene
      end
    elseif segmentID == 2 then --Exiting from Phase 1
      PrintInfo("Phase 1 Defeated")
      SV.stardust_peak.Phase1Defeated = true
      GAME:EnterZone("stardust_peak", -1, 1, 0) -- Send to ground map for cutscene
    elseif segmentID == 3 then --Exiting from phase  two
      SV.stardust_peak.Phase2Defeated = true
      GAME:EnterZone("stardust_peak", -1, 1, 0) -- Send to ground map for cutscene
    end
  end
end

---stardust_peak.Rescued(zone, name, mail)
--Engine callback function
function stardust_peak.Rescued(zone, name, mail)


end

return stardust_peak
