--[[
    init.lua
    Created: 04/25/2025 13:44:17
    Description: Autogenerated script file for the map ending_epilogue.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local ending_epilogue = {}

-------------------------------
-- Map Callbacks
-------------------------------
---ending_epilogue.Init(map)
--Engine callback function
function ending_epilogue.Init(map)
  GAME:CutsceneMode(true)
  --Just play the cutscene
  local cameraX = 192
  local scene1Y = 168
  local scene2Y = 648
  local scene3Y = 1032
  local scene4Y = 1644
  --scene 1
  -- Setup
  local granbull = CH("NPC_Granbull")
  local tsareena = CH("NPC_Tsareena")
  local sneasler = CH("NPC_Sneasler")
  GAME:MoveCamera(cameraX, scene1Y, 1, false)
  --Start
  GAME:FadeIn(20)
  GAME:WaitFrames(30)
  local coro1 = TASK:BranchCoroutine(function() GROUND:MoveInDirection(tsareena, Direction.Up, 72, false, 2) end)
  local coro2 = TASK:BranchCoroutine(function() GROUND:MoveInDirection(sneasler, Direction.Up, 72, false, 2) end)
  TASK:JoinCoroutines({coro1, coro2})

  GAME:WaitFrames(30)
  GROUND:CharSetEmote(tsareena, "happy", 3)
  GROUND:CharSetEmote(sneasler, "happy", 3)
  GAME:WaitFrames(30)
  GROUND:EntTurn(granbull, Direction.Down)
  GROUND:CharSetEmote(granbull, "happy", 16)
  GROUND:CharSetEmote(tsareena, "happy", 16)
  GROUND:CharSetEmote(sneasler, "happy", 16)
  GAME:WaitFrames(120)
  GAME:FadeOut(false, 20)
  --Scene 2 setup
  GAME:WaitFrames(60)
  GAME:MoveCamera(cameraX, scene2Y, 1, false)
  local rayquaza = CH("NPC_Rayquaza")
  --Begin
  GAME:FadeIn(20)
  GAME:WaitFrames(30)
  GROUND:CharSetAnim(rayquaza, "Shoot", false)
  GROUND:CharSetEmote(CH("NPC_Silvally"), "glowing", 8)
  GAME:WaitFrames(120)
  --End
  GAME:FadeOut(false, 20)
  --Scene 3
  COMMON.RespawnAllies()
  local partner = CH("TEAMMATE1")
  GAME:MoveCamera(cameraX, scene3Y, 1, false)
  GAME:WaitFrames(30)
  --STart
  GAME:FadeIn(20)
  GROUND:MoveInDirection(partner, Direction.Down, 168, false, 1)
  GROUND:CharTurnToChar(partner, CH("NPC_Gramps"))
  GROUND:CharTurnToChar(CH("NPC_Gramps"), partner)
  GROUND:CharSetEmote(partner, "glowing", 4)
  GROUND:CharSetEmote(CH("NPC_Gramps"), "happy", 4)
  GAME:WaitFrames(60)
  GROUND:MoveInDirection(partner, Direction.Right, 168, false, 1)
  GAME:WaitFrames(60)
  GAME:FadeOut(false, 20)
  --Full end
  -- Scene 4
  GAME:MoveCamera(cameraX, scene4Y, 1, false)
  GROUND:TeleportTo(partner, cameraX, 1726, Direction.Up)
  GAME:WaitFrames(60)
  --Start
  GAME:FadeIn(20)
  GROUND:MoveInDirection(partner, Direction.Up, 108, false, 1)
  GAME:WaitFrames(120)
  GAME:MoveCamera(cameraX, scene4Y-180, 120, false)

  GAME:WaitFrames(240)
  GAME:FadeOut(false, 20)
  UI:WaitShowVoiceOver("[speed=0.5]The End", 120)
  GAME:CutsceneMode(false)
  GAME:RestartToTitle()
end

---ending_epilogue.Enter(map)
--Engine callback function
function ending_epilogue.Enter(map)

  GAME:FadeIn(20)

end

---ending_epilogue.Exit(map)
--Engine callback function
function ending_epilogue.Exit(map)


end

---ending_epilogue.Update(map)
--Engine callback function
function ending_epilogue.Update(map)


end

---ending_epilogue.GameSave(map)
--Engine callback function
function ending_epilogue.GameSave(map)


end

---ending_epilogue.GameLoad(map)
--Engine callback function
function ending_epilogue.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return ending_epilogue
